### ISSUE TITLE
[Bug]  com.threerings.ClydeLog error when entering the Config window

### ISSUE THREAD

**Issue by Saturos1** [XanTheDragon/ThreeRingsSharp#4]
Following the advice in the video I created a bug report with the error that's happening to me. Currently tested on 2.1.2, 2.1.1 and 2.0.0, but still present.

### What's happening?
When entering for the first time, just after the config window appear on screen, an error shows:
```
The type initializer for com.threerings.ClydeLog threw an exception.
The type initializer for com.threerings.ClydeLog threw an exception.
This program cannot continue when this error occurs and must exit, as this data is 100% required for it to function properly.
```

### What settings?
It happens with any kind of modification of the threeringssharp.cfg file, by default or changing values (deleting the paths, changing them to a correct one, changing them to a different path...).

If I set the "IsFirstTimeOpening" flag to false (just to test), it skips the config window but the error still happens.

### How do I make it happen?
Opening the SKAnimatorTools.exe file directly make it appear.

Thanks!

**Comment by XanTheDragon** [comment]
This is an issue a number of people have had for reasons I don't really understand to be honest. I'll continue looking into it.

A `TypeInitializationException` effectively means that the code that sets an object up before the program uses it has errored -- This should happen to *everyone* if it's this kind of error, but it doesn't, which makes about as much sense as 2+2=48949.

Could you send latest.log?

**Comment by XanTheDragon** [comment]
Bit of a status update, this seems to be an issue with IKVM (translates Java to C#) on systems with a non-English language and a missing DLL that Visual Studio thinks it doesn't need. I'm testing this privately and will update the issue at the nearest opportunity.

**Comment by Saturos1** [comment]
> 
> 
> This is an issue a number of people have had for reasons I don't really understand to be honest. I'll continue looking into it.
> 
> A `TypeInitializationException` effectively means that the code that sets an object up before the program uses it has errored -- This should happen to _everyone_ if it's this kind of error, but it doesn't, which makes about as much sense as 2+2=48949.
> 
> Could you send latest.log?

[latest.log](https://github.com/XanTheDragon/ThreeRingsSharp/files/5141109/latest.log)
Sure. I've attached the log. Basically what it says in spanish is "Can't convert the object type 'java.util.PropertyResourceBundle' to 'sun.util.resources.OpenListResourceBundle' type"


> 
> 
> Bit of a status update, this seems to be an issue with IKVM (translates Java to C#) on systems with a non-English language and a missing DLL that Visual Studio thinks it doesn't need. I'm testing this privately and will update the issue at the nearest opportunity.

My system is in Spanish so it makes sense. Thanks for the effort!

**Comment by XanTheDragon** [comment]
Alright. I've gotten the issue nailed down it seems. I'll have a release out in a moment.

**Comment by XanTheDragon** [comment]
Alrighty. This should be resolved in 2.1.3.

**Comment by Saturos1** [comment]
Thanks! But I have some bad news.... it's still happening to me in 2.1.3 :(
The error shows the same (it's not a different one just in case) and the content of the latest.log is the same too...

If you need me to test something in my environment let me know here or by steam (mehdow)

![imagen](https://user-images.githubusercontent.com/69110552/91553194-48a82280-e92d-11ea-8ed0-db16c635033f.png)

**Comment by Saturos1** [comment]
I have just installed the English language package and set it in Windows, and now everything works fine, so yeah it is a thing related to language...
